---
- hosts: localhost

  tasks:
    - name: detect roles/requirements.(yml/yaml)
      stat:
        path: "/var/lib/awx/projects//playbook-testing/_12__test_playbook/roles/requirements.yml"
      with_items: "Ok"
      register: doesRequirementsExist

